# -*- coding: utf-8 -*-
"""Pima Indians Diabetes Database.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Piokbd2oLb1Me6WpXCoHqENfBJopfhk5

# **download data from kaggle**
"""

import os
os.environ['KAGGLE_USERNAME'] = "belalagwa"  # username from the json file
os.environ['KAGGLE_KEY'] = "c30180e65b45212ab6c1fe4688732366"  # key from the json file
!kaggle datasets download -d uciml/pima-indians-diabetes-database # api copied from kaggle

!unzip /content/pima-indians-diabetes-database.zip

import pickle
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
np.random.seed(42)

#load data
load_data=pd.read_csv(r"/content/diabetes.csv")

#view sample data
print(load_data.head())

# handel missing data

print(load_data.info())

#  map labled data 
X=load_data.drop('Outcome',axis=1)
y=load_data['Outcome']

#split data to train \ test

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# tune model parms

from sklearn.model_selection import GridSearchCV
prams={"kernel":("linear","rbf"), "C":[1,5,10], "gamma":[1,0.1,0.01,0.001]}
grid=GridSearchCV(svm.SVC(),prams,verbose=3)
grid.fit(x_train,y_train)

print(grid.best_params_)
print(grid.best_score_)

#choose model

model=svm.SVC(C=1, gamma= 1, kernel='linear')

#train model

model.fit(x_train,y_train)

print(model.score(x_train , y_train))
print(model.score(x_test , y_test))

from sklearn.neighbors import KNeighborsClassifier
model1 = KNeighborsClassifier(n_neighbors=3)

model1.fit(x_train,y_train)

print(model1.score(x_train , y_train))
print(model1.score(x_test , y_test))

from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
bagging = BaggingClassifier(KNeighborsClassifier(), max_samples=0.5, max_features=0.5)

bagging.fit(x_train,y_train)

print(bagging.score(x_train , y_train))
print(bagging.score(x_test , y_test))